service: aws-lambda-client-ip

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  myIP:
    handler: handler.myIP
    events:
      - http:
          path: myip
          method: get
